# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{schema_hash}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David James"]
  s.date = %q{2009-10-08}
  s.description = %q{Is your hash in shape? We can help.}
  s.email = %q{djames@sunlightfoundation.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/hash.rb",
     "lib/schema_hash.rb",
     "lib/schemable.rb",
     "lib/traversable.rb",
     "schema_hash.gemspec",
     "spec/hash_spec.rb",
     "spec/spec_helper.rb",
     "spec/traversable_spec.rb"
  ]
  s.homepage = %q{http://github.com/djsun/schema_hash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Validates a hash against a schema.}
  s.test_files = [
    "spec/hash_spec.rb",
     "spec/spec_helper.rb",
     "spec/traversable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
